
## Static graph (TensorFlow 1.x) vs Eager execution (TensorFlow 2.0)

![alt text](https://www.tensorflow.org/images/tensors_flowing.gif)
*Image take from: https://www.tensorflow.org/guide/graphs*


## TensorFlow 1.X




### Installing TensorFlow 1.X



In [1]:
!pip install tensorflow-gpu

ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.13.1 (from versions: 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.6.0rc0)
ERROR: No matching distribution found for tensorflow-gpu==1.13.1


In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'1.13.1'

### Variables and constants in TF 1.x

#### Variables

In [ ]:
#Initialize normal Variable in tf 1.x
variable = tf.Variable([[30, 20], [10, 45]])

In [ ]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32_ref>

In [ ]:
#Getting shape of the variable
variable.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [ ]:
#Performing addition operation on the tensor produces another tf.Tensor object
variable + 2

<tf.Tensor 'add_1:0' shape=(2, 2) dtype=int32>

In [ ]:
#If a session is not initialized we cannot access values in the Variable/Tensor
variable.eval()

ValueError: ignored

In [ ]:
#Able to slice a variable, but we are still not able to retrive values from it
variable[:1]

<tf.Tensor 'strided_slice_2:0' shape=(1, 2) dtype=int32>

#### Getting values from variables

In [ ]:
#Initialize session
session = tf.Session()

In [ ]:
#Initialize ALL variables for the session
session.run(tf.global_variables_initializer())

In [ ]:
#Run the eval method on the evironment with provided session to retrive values from it
variable.eval(session)

array([[30, 20],
       [10, 45]], dtype=int32)

#### Constants/Tensors

In [ ]:
#Define a TensorFlow constant matrix
tensor = tf.constant([[23, 4], [32, 51]])

In [ ]:
tensor

<tf.Tensor 'Const:0' shape=(2, 2) dtype=int32>

In [ ]:
#We are still not able to get the real value without defining a session
tensor.eval()

ValueError: ignored

#### Getting values from constants

In [ ]:
session = tf.Session()

In [ ]:
session.run(tf.global_variables_initializer())

In [ ]:
#Fatching the tensor from the tensor graph/session
tensor_value = session.run(tensor)

In [ ]:
tensor_value

array([[23,  4],
       [32, 51]], dtype=int32)

## TensorFlow 2.0

### Installing TensorFlow 2.0

In [2]:
!pip install tensorflow-gpu

  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
  Using cached termcolor-1.1.0.tar.gz (3.9 kB)
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Using legacy 'setup.py install' for termcolor, since package 'wheel' is not installed.
Using legacy 'setup.py install' for wrapt, since package 'wheel' is not installed.
  Attempting uninstall: six
    Found existing installation: six 1.16.0
    Uninstalling six-1.16.0:
      Successfully uninstalled six-1.16.0
    Running setup.py install for wrapt: started
    Running setup.py install for wrapt: finished with status 'done'
  Attempting uninstall: typing-extensions
    Found existing installation: typing-extensions 3.10.0.0
    Uninstalling typing-extensions-3.10.0.0:
      Successfully uninstalled typing-extensions-3.10.0.0
    Running setup.p

In [3]:
import tensorflow as tf
import numpy as np

In [4]:
tf.__version__

'2.5.0'

### Constants/Tensors

In [5]:
#Defining a constant in TensorFlow 2.0
tensor_20 = tf.constant([[23, 4], [32, 51]])

In [6]:
tensor_20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]])>

In [7]:
#Getting shape of a tensor
tensor_20.shape

TensorShape([2, 2])

### Getting values from constants

In [8]:
#Getting values straight from a TensorFlow constant to numpy - withut sesion
tensor_20.numpy()

array([[23,  4],
       [32, 51]])

In [9]:
#We are able to convert a numpy matrix back to a TensorFlow tensor as well
numpy_tensor = np.array([[23,  4], [32, 51]])

In [10]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [11]:
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]])>

### Operations with constants/tensors

In [12]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

#### Addition between scalar and tensor

In [13]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]])>

#### Multiplication between scalar and tensor

In [14]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]])>

#### Using Numpy functions on TensorFlow tensors

In [ ]:
#Squaring all numbers in a tensorflow tensor object
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [ ]:
#Square root of all numbers in a tensorflow tensor object
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

#### Dot product between two tensors

In [ ]:
 np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

### Operations with variables

In [ ]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

#### Getting raw value from the variable

In [ ]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

#### Changing specific value in the TensorFlow variable

In [ ]:
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [ ]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Strings in TensorFlow 2.0

In [ ]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: id=62, shape=(), dtype=string, numpy=b'TensorFlow'>

#### Simple string operations

In [ ]:
tf.strings.length(tf_string)

<tf.Tensor: id=49, shape=(), dtype=int32, numpy=10>

In [ ]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: id=58, shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

### Storing arrays of strings

In [ ]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [ ]:
#How to iterate through the TF string array
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)


### Handling Devices in TensorFlow 2.0

#### CPU

In [ ]:
with tf.device("/cpu:0"):
    tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [ ]:
tf_string_array.device

'/job:localhost/replica:0/task:0/device:CPU:0'

#### GPU

In [ ]:
if tf.test.is_gpu_available():
    with tf.device("/gpu:0"):
        tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])
    print(tf_string_array.device)